dataset:
  num_classes: 19
  training:
    video_mp4_path: /raid/aicity/data/A1/validation/
    video_info_path: /raid/aicity/data/A1/val_video_info1.csv
    video_anno_path: /raid/aicity/data/A1/anno_val1.csv
    video_data_path: /raid/aicity/data/A1/validation_npy/
    clip_length: 256
    clip_stride: 30
    crop_size: 96
  testing:
    video_mp4_path: /home/xyc/AICity/data # /xxxx/Aicity/videos
    video_info_path: /home/xyc/data/AICity/info/test_video_info.csv # /xxxx/Aicity/info/test_video_info.csv
    video_anno_path: /home/xyc/data/AICity/anno/test_Annotation_ours.csv # Not used
    video_data_path: /home/xyc/AICity/dataB # /xxxx/Aicity/dataNPY
    crop_size: 96
    clip_length: 256
    clip_stride: 128

model:
  in_channels: 3
  freeze_bn: true
  freeze_bn_affine: true
  backbone_model: /home/xyc/AICity/aicity/aicity/ActionDetection-AFSD-master/ActionDetection-AFSD-master/models/thumos14/ckp/rgb_imagenet.pt

training:
  batch_size: 2
  learning_rate: 1e-7
  weight_decay: 1e-3
  max_epoch: 160
  focal_loss: true
  checkpoint_path: ./models/thumos14_1/
  random_seed: 2020

testing:
  conf_thresh: 0.01
  top_k: 5000
  nms_thresh: 0.5
  nms_sigma: 0.5
  checkpoint_path: /home/xyc/AICity/aicity/aicity/ActionDetection-AFSD-master/ActionDetection-AFSD-master/models/thumos14/checkpoint-150.ckpt # TODO checkpoint-150.ckpt's dir.
  output_path: ./output
  output_json: detection_results.json
